name: Deploy Terraform Portfolio
run-name: Deploy ${{ inputs.project }} infrastructure

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Which project are we deploying?'
        required: true
        type: choice
        options:
          - nicoxmcdportfolio
          - nicolexanportfolio
      dry_run:
        description: 'True for PLAN ONLY'
        required: true
        default: true
        type: boolean

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  Terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./Terraform/${{ inputs.project }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Unit Tests
      run: |
        export PYTHONPATH=.
        python tests/test_count.py

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.0 

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.ROLE_DEPLOY }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: us-east-1

    - name: Terraform Init
      run: |
        # terraform init
        # from the repo dir with the same backend config
        terraform init -reconfigure
        terraform force-unlock -force 5f647782-f964-009a-c73c-b6993cff9294


    - name: Terraform Plan
      run: |
        terraform plan -lock-timeout=5m
        
    - name: Terraform Apply
      if: ${{ inputs.dry_run == false }}
      run: |
        terraform apply -auto-approve -lock-timeout=5m
    
    # - name: Invalidate CloudFront Cache
    #   if: ${{ inputs.dry_run == false }}
    #   run: |
    #     var=`cat distribution.txt`
    #     aws cloudfront create-invalidation \
    #       --distribution-id $var \
    #       --paths "/*"
